/*
 * Copyright (c) 2024 Cach30verfl0w
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package de.cacheoverflow.fints.formals.enums

/**
 * This enum contains a list of all currencies specified in ISO 4217 with the name, symbol and major
 * single name of the currency. This complete list was auto-generated with the help of the table on
 * Wikipedia. So I can't guarantee the correctness of the enum's information.
 *
 * @see [ISO 4217 on Wikipedia](https://en.wikipedia.org/wiki/ISO_4217)
 *
 * @author Cedric Hammes
 * @since  26/06/2024
 */
enum class EnumCurrency(val symbol: String, val formalName: String, val majorSingle: String) {

    UNITED_ARAB_EMIRATES_DIRHAM("د.إ.", "United Arab Emirates Dirham", "Dirham"),
    AFGHAN_AFGHANI("Af", "Afghan Afghani", "Afghani"),
    ALBANIAN_LEK("L", "Albanian Lek", "Lek"),
    ARMENIAN_DRAM("֏", "Armenian Dram", "Dram"),
    NETHERLANDS_ANTILLEAN_GUILDER("ƒ", "Netherlands Antillean Guilder", "Guilder"),
    ANGOLAN_KWANZA("Kz", "Angolan Kwanza", "Kwanza"),
    ARGENTINE_PESO("AR$", "Argentine Peso", "Peso"),
    AUSTRALIAN_DOLLAR("AU$", "Australian Dollar", "Dollar"),
    ARUBAN_FLORIN("ƒ", "Aruban Florin", "Florin"),
    AZERBAIJANI_MANAT("ман", "Azerbaijani Manat", "Manat"),
    BOSNIA_AND_HERZEGOVINA_CONVERTIBLE_MARK("KM", "Bosnia and Herzegovina Convertible Mark", "Convertible Mark"),
    BARBADIAN_DOLLAR("BBD$", "Barbadian Dollar", "Dollar"),
    BANGLADESHI_TAKA("৳", "Bangladeshi Taka", "Taka"),
    BULGARIAN_LEV("лв.", "Bulgarian Lev", "Lev"),
    BAHRAINI_DINAR("BD", "Bahraini Dinar", "Dinar"),
    BURUNDIAN_FRANC("FBu", "Burundian Franc", "Franc"),
    BERMUDIAN_DOLLAR("$", "Bermudian Dollar", "Dollar"),
    BRUNEI_DOLLAR("B$", "Brunei Dollar", "Dollar"),
    BOLIVIAN_BOLIVIANO("Bs.", "Bolivian Boliviano", "Boliviano"),
    BRAZILIAN_REAL("R$", "Brazilian Real", "Real"),
    BAHAMIAN_DOLLAR("$", "Bahamian Dollar", "Dollar"),
    BHUTANESE_NGULTRUM("Nu.", "Bhutanese Ngultrum", "Ngultrum"),
    BOTSWANA_PULA("P", "Botswana Pula", "Pula"),
    BELARUSIAN_RUBLE("Br", "Belarusian Ruble", "Ruble"),
    BELIZE_DOLLAR("BZ$", "Belize Dollar", "Dollar"),
    CANADIAN_DOLLAR("CA$", "Canadian Dollar", "Dollar"),
    CONGOLESE_FRANC("FC", "Congolese Franc", "Franc"),
    SWISS_FRANC("Fr.", "Swiss Franc", "Franc"),
    COOK_ISLANDS_DOLLAR("$", "Cook Islands Dollar", "Dollar"),
    CHILEAN_PESO("CL$", "Chilean Peso", "Peso"),
    CHINESE_YUAN("CN¥", "Chinese Yuan", "Yuan"),
    COLOMBIAN_PESO("CO$", "Colombian Peso", "Peso"),
    COSTA_RICAN_COLON("₡", "Costa Rican Colon", "Colón"),
    CUBAN_CONVERTIBLE_PESO("CUC$", "Cuban convertible Peso", "Peso"),
    CUBAN_PESO("\$MN", "Cuban Peso", "Peso"),
    CABO_VERDEAN_ESCUDO("CV$", "Cabo Verdean Escudo", "Escudo"),
    CZECH_KORUNA("Kč", "Czech Koruna", "Koruna"),
    DJIBOUTIAN_FRANC("Fdj", "Djiboutian Franc", "Franc"),
    DANISH_KRONE("kr.", "Danish Krone", "Krone"),
    DOMINICAN_PESO("RD$", "Dominican Peso", "Peso"),
    ALGERIAN_DINAR("DA", "Algerian Dinar", "Dinar"),
    EGYPTIAN_POUND("E£", "Egyptian Pound", "Pound"),
    SAHRAWI_PESETA("Ptas.", "Sahrawi Peseta", "Peseta"),
    ERITREAN_NAKFA("Nkf", "Eritrean Nakfa", "Nakfa"),
    ETHIOPIAN_BIRR("Br", "Ethiopian Birr", "Birr"),
    EURO("€", "Euro", "Euro"),
    FIJIAN_DOLLAR("FJ$", "Fijian Dollar", "Dollar"),
    FALKLAND_ISLANDS_POUND("FK£", "Falkland Islands Pound", "Pound"),
    FAROESE_KRONA("kr", "Faroese Króna", "Króna"),
    POUND_STERLING("£", "Pound Sterling", "Pound"),
    GEORGIAN_LARI("₾", "Georgian Lari", "Lari"),
    GUERNSEY_POUND("£", "Guernsey Pound", "Pound"),
    GHANAIAN_CEDI("GH₵", "Ghanaian Cedi", "Cedi"),
    GIBRALTAR_POUND("£", "Gibraltar Pound", "Pound"),
    GAMBIAN_DALASI("D", "Gambian Dalasi", "Dalasi"),
    GUINEAN_FRANC("FG", "Guinean Franc", "Franc"),
    GUATEMALAN_QUETZAL("Q", "Guatemalan Quetzal", "Quetzal"),
    GUYANESE_DOLLAR("G$", "Guyanese Dollar", "Dollar"),
    HONG_KONG_DOLLAR("HK$", "Hong Kong Dollar", "Dollar"),
    HONDURAN_LEMPIRA("L", "Honduran Lempira", "Lempira"),
    CROATIAN_KUNA("kn", "Croatian Kuna", "Kuna"),
    HAITIAN_GOURDE("G", "Haitian Gourde", "Gourde"),
    HUNGARIAN_FORINT("Ft", "Hungarian Forint", "Forint"),
    INDONESIAN_RUPIAH("Rp", "Indonesian Rupiah", "Rupiah"),
    ISRAELI_NEW_SHEKEL("₪", "Israeli new Shekel", "Shekel"),
    MANX_POUND("£", "Manx Pound", "Pound"),
    INDIAN_RUPEE("Rs.", "Indian Rupee", "Rupee"),
    IRAQI_DINAR("د.ع.", "Iraqi Dinar", "Dinar"),
    IRANIAN_RIAL("﷼", "Iranian Rial", "Rial"),
    ICELANDIC_KRONA("kr", "Icelandic Krona", "Krona"),
    JERSEY_POUND("£", "Jersey Pound", "Pound"),
    JAMAICAN_DOLLAR("J$", "Jamaican Dollar", "Dollar"),
    JORDANIAN_DINAR("JD", "Jordanian Dinar", "Dinar"),
    JAPANESE_YEN("¥", "Japanese Yen", "Yen"),
    KENYAN_SHILLING("KSh", "Kenyan Shilling", "Shilling"),
    KYRGYZSTANI_SOM("с", "Kyrgyzstani Som", "Som"),
    CAMBODIAN_RIEL("៛", "Cambodian Riel", "Riel"),
    KIRIBATI_DOLLAR("$", "Kiribati Dollar", "Dollar"),
    COMORIAN_FRANC("CF", "Comorian Franc", "Franc"),
    NORTH_KOREAN_WON("₩", "North Korean Won", "Won"),
    SOUTH_KOREAN_WON("₩", "South Korean Won", "Won"),
    KUWAITI_DINAR("KD", "Kuwaiti Dinar", "Dinar"),
    CAYMAN_ISLANDS_DOLLAR("CI$", "Cayman Islands Dollar", "Dollar"),
    KAZAKHSTANI_TENGE("₸", "Kazakhstani Tenge", "Tenge"),
    LAO_KIP("₭N", "Lao Kip", "Kip"),
    LEBANESE_POUND("LL.", "Lebanese Pound", "Pound"),
    SRI_LANKAN_RUPEE("Rs.", "Sri Lankan Rupee", "Rupee"),
    LIBERIAN_DOLLAR("L$", "Liberian Dollar", "Dollar"),
    LESOTHO_LOTI("L", "Lesotho Loti", "Loti"),
    LIBYAN_DINAR("LD", "Libyan Dinar", "Dinar"),
    MOROCCAN_DIRHAM("DH", "Moroccan Dirham", "Dirham"),
    MOLDOVAN_LEU("L", "Moldovan Leu", "Leu"),
    MALAGASY_ARIARY("Ar", "Malagasy Ariary", "Ariary"),
    MACEDONIAN_DENAR("den", "Macedonian Denar", "Denar"),
    MYANMAR_KYAT("Ks", "Myanmar Kyat", "Kyat"),
    MONGOLIAN_TOGROG("₮", "Mongolian Tögrög", "Tögrög"),
    MACANESE_PATACA("MOP$", "Macanese Pataca", "Pataca"),
    MAURITANIAN_OUGUIYA("UM", "Mauritanian Ouguiya", "Ouguiya"),
    MAURITIAN_RUPEE("Rs.", "Mauritian Rupee", "Rupee"),
    MALDIVIAN_RUFIYAA("MRf", "Maldivian Rufiyaa", "Rufiyaa"),
    MALAWIAN_KWACHA("MK", "Malawian Kwacha", "Kwacha"),
    MEXICAN_PESO("MX$", "Mexican Peso", "Peso"),
    MALAYSIAN_RINGGIT("RM", "Malaysian Ringgit", "Ringgit"),
    MOZAMBICAN_METICAL("MTn", "Mozambican Metical", "Metical"),
    NAMIBIAN_DOLLAR("N$", "Namibian Dollar", "Dollar"),
    NIGERIAN_NAIRA("₦", "Nigerian Naira", "Naira"),
    NICARAGUAN_CORDOBA("C$", "Nicaraguan Córdoba", "Córdoba Oro"),
    NORWEGIAN_KRONE("kr", "Norwegian Krone", "Krone"),
    NEPALESE_RUPEE("Rs.", "Nepalese Rupee", "Rupee"),
    NEW_ZEALAND_DOLLAR("NZ$", "New Zealand Dollar", "Dollar"),
    OMANI_RIAL("OR", "Omani Rial", "Rial"),
    PANAMANIAN_BALBOA("B/.", "Panamanian Balboa", "Balboa"),
    PERUVIAN_SOL("S/.", "Peruvian Sol", "Sol"),
    PAPUA_NEW_GUINEAN_KINA("K", "Papua New Guinean Kina", "Kina"),
    PHILIPPINE_PESO("₱", "Philippine Peso", "Peso"),
    PAKISTANI_RUPEE("Rs.", "Pakistani Rupee", "Rupee"),
    POLISH_ZLOTY("zł", "Polish Zloty", "Zloty"),
    PITCAIRN_ISLANDS_DOLLAR("$", "Pitcairn Islands Dollar", "Dollar"),
    TRANSNISTRIAN_RUBLE("р.", "Transnistrian Ruble", "Ruble"),
    PARAGUAYAN_GUARANI("₲", "Paraguayan Guaraní", "Guaraní"),
    QATARI_RIYAL("QR", "Qatari Riyal", "Riyal"),
    ROMANIAN_LEU("L", "Romanian Leu", "Leu"),
    SERBIAN_DINAR("din", "Serbian Dinar", "Dinar"),
    RUSSIAN_RUBLE("₽", "Russian Ruble", "Ruble"),
    RWANDAN_FRANC("FRw", "Rwandan Franc", "Franc"),
    SAUDI_RIYAL("SR", "Saudi Riyal", "Riyal"),
    SOLOMON_ISLANDS_DOLLAR("SI$", "Solomon Islands Dollar", "Dollar"),
    SEYCHELLOIS_RUPEE("Rs.", "Seychellois Rupee", "Rupee"),
    SUDANESE_POUND("£SD", "Sudanese Pound", "Pound"),
    SWEDISH_KRONA("kr", "Swedish Krona", "Krona"),
    SINGAPORE_DOLLAR("S$", "Singapore Dollar", "Dollar"),
    SAINT_HELENA_POUND("£", "Saint Helena Pound", "Pound"),
    SIERRA_LEONEAN_LEONE("Le", "Sierra Leonean Leone", "Leone"),
    SOMALILAND_SHILLING("Sl", "Somaliland Shilling", "Shilling"),
    SOMALI_SHILLING("Sh.So.", "Somali Shilling", "Shilling"),
    SURINAMESE_DOLLAR("Sr$", "Surinamese Dollar", "Dollar"),
    SOUTH_SUDANESE_POUND("SS£", "South Sudanese Pound", "Pound"),
    SAO_TOME_AND_PRINCIPE_DOBRA("Db", "Sao Tome and Príncipe Dobra", "Dobra"),
    SALVADORAN_COLON("₡", "Salvadoran Colón", "Colón"),
    SYRIAN_POUND("LS", "Syrian Pound", "Pound"),
    SWAZI_LILANGENI("L", "Swazi Lilangeni", "Lilangeni"),
    THAI_BAHT("฿", "Thai Baht", "Baht"),
    TAJIKISTANI_SOMONI("SM", "Tajikistani Somoni", "Somoni"),
    TURKMENISTAN_MANAT("m.", "Turkmenistan Manat", "Manat"),
    TUNISIAN_DINAR("DT", "Tunisian Dinar", "Dinar"),
    TONGAN_PAANGA("T$", "Tongan Paʻanga", "Pa'anga"),
    TURKISH_LIRA("TL", "Turkish Lira", "Lira"),
    TRINIDAD_AND_TOBAGO_DOLLAR("TT$", "Trinidad and Tobago Dollar", "Dollar"),
    TUVALUAN_DOLLAR("$", "Tuvaluan Dollar", "Dollar"),
    NEW_TAIWAN_DOLLAR("NT$", "New Taiwan Dollar", "Dollar"),
    TANZANIAN_SHILLING("TSh", "Tanzanian Shilling", "Shilling"),
    UKRAINIAN_HRYVNIA("₴", "Ukrainian Hryvnia", "Hryvnia"),
    UGANDAN_SHILLING("USh", "Ugandan Shilling", "Shilling"),
    UNITED_STATES_DOLLAR("$", "United States Dollar", "Dollar"),
    URUGUAYAN_PESO("\$U", "Uruguayan Peso", "Peso"),
    UZBEKISTANI_SOM("сум", "Uzbekistani Som", "Som"),
    VENEZUELAN_BOLIVAR_DIGITAL("Bs.", "Venezuelan bolívar digital", "Bolívar Digital"),
    VENEZUELAN_BOLIVAR_SOBERANO("Bs.F", "Venezuelan Bolívar Soberano", "Bolívar"),
    VIETNAMESE_DONG("₫", "Vietnamese Dong", "Dong"),
    VANUATU_VATU("VT", "Vanuatu Vatu", "Vatu"),
    SAMOAN_TALA("T", "Samoan Tala", "Tala"),
    CENTRAL_AFRICAN_CFA_FRANC_BEAC("Fr", "Central African CFA Franc BEAC", "Franc"),
    EAST_CARIBBEAN_DOLLAR("$", "East Caribbean Dollar", "Dollar"),
    WEST_AFRICAN_CFA_FRANC_BCEAO("₣", "West African CFA Franc BCEAO", "Franc"),
    CFP_FRANC_FRANC_PACIFIQUE("₣", "CFP Franc (Franc Pacifique)", "Franc"),
    YEMENI_RIAL("YR", "Yemeni Rial", "Rial"),
    SOUTH_AFRICAN_RAND("R", "South African Rand", "Rand"),
    ZAMBIAN_KWACHA("ZK", "Zambian Kwacha", "Kwacha"),
    RTGS_DOLLAR("", "RTGS Dollar", "Dollar"),
    ZIMBABWEAN_DOLLAR("Z$", "Zimbabwean Dollar", "Dollar"),
    ABKHAZIAN_APSAR("", "Abkhazian Apsar", "Apsar"),
    ARTSAKH_DRAM("դր.", "Artsakh Dram", "Dram"),

}
