/*
 * Copyright (c) 2024 Cach30verfl0w
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package de.cacheoverflow.fints.formals.enums

/**
 * This enum contains a list of all countries specified in ISO 3166-1 with the name, Alpha-2 and
 * Alpha-3 code of the country. This complete list was auto-generated with the help of the table
 * on Wikipedia. So I can't guarantee the correctness of the enum's information.
 *
 * @see [ISO 3166-1 on Wikipedia](https://en.wikipedia.org/wiki/ISO_3166-1)
 *
 * @author Cedric Hammes
 * @since  26/06/2024
 */
enum class EnumCountry(val alpha2Code: String, val alpha3Code: String, val shortName: String) {

    AFGHANISTAN("AF", "AFG", "Afghanistan"),
    ALAND_ISLANDS("AX", "ALA", "Åland Islands"),
    ALBANIA("AL", "ALB", "Albania"),
    ALGERIA("DZ", "DZA", "Algeria"),
    AMERICAN_SAMOA("AS", "ASM", "American Samoa"),
    ANDORRA("AD", "AND", "Andorra"),
    ANGOLA("AO", "AGO", "Angola"),
    ANGUILLA("AI", "AIA", "Anguilla"),
    ANTARCTICA("AQ", "ATA", "Antarctica"),
    ANTIGUA_AND_BARBUDA("AG", "ATG", "Antigua and Barbuda"),
    ARGENTINA("AR", "ARG", "Argentina"),
    ARMENIA("AM", "ARM", "Armenia"),
    ARUBA("AW", "ABW", "Aruba"),
    AUSTRALIA("AU", "AUS", "Australia"),
    AUSTRIA("AT", "AUT", "Austria"),
    AZERBAIJAN("AZ", "AZE", "Azerbaijan"),
    BAHAMAS("BS", "BHS", "Bahamas"),
    BAHRAIN("BH", "BHR", "Bahrain"),
    BANGLADESH("BD", "BGD", "Bangladesh"),
    BARBADOS("BB", "BRB", "Barbados"),
    BELARUS("BY", "BLR", "Belarus"),
    BELGIUM("BE", "BEL", "Belgium"),
    BELIZE("BZ", "BLZ", "Belize"),
    BENIN("BJ", "BEN", "Benin"),
    BERMUDA("BM", "BMU", "Bermuda"),
    BHUTAN("BT", "BTN", "Bhutan"),
    BOLIVIA_PLURINATIONAL_STATE_OF("BO", "BOL", "Bolivia, Plurinational State of"),
    BONAIRE_SINT_EUSTATIUS_AND_SABA("BQ", "BES", "Bonaire, Sint Eustatius and Saba"),
    BOSNIA_AND_HERZEGOVINA("BA", "BIH", "Bosnia and Herzegovina"),
    BOTSWANA("BW", "BWA", "Botswana"),
    BOUVET_ISLAND("BV", "BVT", "Bouvet Island"),
    BRAZIL("BR", "BRA", "Brazil"),
    BRITISH_INDIAN_OCEAN_TERRITORY("IO", "IOT", "British Indian Ocean Territory"),
    BRUNEI_DARUSSALAM("BN", "BRN", "Brunei Darussalam"),
    BULGARIA("BG", "BGR", "Bulgaria"),
    BURKINA_FASO("BF", "BFA", "Burkina Faso"),
    BURUNDI("BI", "BDI", "Burundi"),
    CABO_VERDE("CV", "CPV", "Cabo Verde"),
    CAMBODIA("KH", "KHM", "Cambodia"),
    CAMEROON("CM", "CMR", "Cameroon"),
    CANADA("CA", "CAN", "Canada"),
    CAYMAN_ISLANDS("KY", "CYM", "Cayman Islands"),
    CENTRAL_AFRICAN_REPUBLIC("CF", "CAF", "Central African Republic"),
    CHAD("TD", "TCD", "Chad"),
    CHILE("CL", "CHL", "Chile"),
    CHINA("CN", "CHN", "China"),
    CHRISTMAS_ISLAND("CX", "CXR", "Christmas Island"),
    COCOS_KEELING_ISLANDS("CC", "CCK", "Cocos (Keeling) Islands"),
    COLOMBIA("CO", "COL", "Colombia"),
    COMOROS("KM", "COM", "Comoros"),
    CONGO("CG", "COG", "Congo"),
    CONGO_DEMOCRATIC_REPUBLIC_OF_THE("CD", "COD", "Congo, Democratic Republic of the"),
    COOK_ISLANDS("CK", "COK", "Cook Islands"),
    COSTA_RICA("CR", "CRI", "Costa Rica"),
    COTE_DIVOIRE("CI", "CIV", "Côte d'Ivoire"),
    CROATIA("HR", "HRV", "Croatia"),
    CUBA("CU", "CUB", "Cuba"),
    CURACAO("CW", "CUW", "Curaçao"),
    CYPRUS("CY", "CYP", "Cyprus"),
    CZECHIA("CZ", "CZE", "Czechia"),
    DENMARK("DK", "DNK", "Denmark"),
    DJIBOUTI("DJ", "DJI", "Djibouti"),
    DOMINICA("DM", "DMA", "Dominica"),
    DOMINICAN_REPUBLIC("DO", "DOM", "Dominican Republic"),
    ECUADOR("EC", "ECU", "Ecuador"),
    EGYPT("EG", "EGY", "Egypt"),
    EL_SALVADOR("SV", "SLV", "El Salvador"),
    EQUATORIAL_GUINEA("GQ", "GNQ", "Equatorial Guinea"),
    ERITREA("ER", "ERI", "Eritrea"),
    ESTONIA("EE", "EST", "Estonia"),
    ESWATINI("SZ", "SWZ", "Eswatini"),
    ETHIOPIA("ET", "ETH", "Ethiopia"),
    FALKLAND_ISLANDS_MALVINAS("FK", "FLK", "Falkland Islands (Malvinas)"),
    FAROE_ISLANDS("FO", "FRO", "Faroe Islands"),
    FIJI("FJ", "FJI", "Fiji"),
    FINLAND("FI", "FIN", "Finland"),
    FRANCE("FR", "FRA", "France"),
    FRENCH_GUIANA("GF", "GUF", "French Guiana"),
    FRENCH_POLYNESIA("PF", "PYF", "French Polynesia"),
    FRENCH_SOUTHERN_TERRITORIES("TF", "ATF", "French Southern Territories"),
    GABON("GA", "GAB", "Gabon"),
    GAMBIA("GM", "GMB", "Gambia"),
    GEORGIA("GE", "GEO", "Georgia"),
    GERMANY("DE", "DEU", "Germany"),
    GHANA("GH", "GHA", "Ghana"),
    GIBRALTAR("GI", "GIB", "Gibraltar"),
    GREECE("GR", "GRC", "Greece"),
    GREENLAND("GL", "GRL", "Greenland"),
    GRENADA("GD", "GRD", "Grenada"),
    GUADELOUPE("GP", "GLP", "Guadeloupe"),
    GUAM("GU", "GUM", "Guam"),
    GUATEMALA("GT", "GTM", "Guatemala"),
    GUERNSEY("GG", "GGY", "Guernsey"),
    GUINEA("GN", "GIN", "Guinea"),
    GUINEA_BISSAU("GW", "GNB", "Guinea-Bissau"),
    GUYANA("GY", "GUY", "Guyana"),
    HAITI("HT", "HTI", "Haiti"),
    HEARD_ISLAND_AND_MCDONALD_ISLANDS("HM", "HMD", "Heard Island and McDonald Islands"),
    HOLY_SEE("VA", "VAT", "Holy See"),
    HONDURAS("HN", "HND", "Honduras"),
    HONG_KONG("HK", "HKG", "Hong Kong"),
    HUNGARY("HU", "HUN", "Hungary"),
    ICELAND("IS", "ISL", "Iceland"),
    INDIA("IN", "IND", "India"),
    INDONESIA("ID", "IDN", "Indonesia"),
    IRAN_ISLAMIC_REPUBLIC_OF("IR", "IRN", "Iran, Islamic Republic of"),
    IRAQ("IQ", "IRQ", "Iraq"),
    IRELAND("IE", "IRL", "Ireland"),
    ISLE_OF_MAN("IM", "IMN", "Isle of Man"),
    ISRAEL("IL", "ISR", "Israel"),
    ITALY("IT", "ITA", "Italy"),
    JAMAICA("JM", "JAM", "Jamaica"),
    JAPAN("JP", "JPN", "Japan"),
    JERSEY("JE", "JEY", "Jersey"),
    JORDAN("JO", "JOR", "Jordan"),
    KAZAKHSTAN("KZ", "KAZ", "Kazakhstan"),
    KENYA("KE", "KEN", "Kenya"),
    KIRIBATI("KI", "KIR", "Kiribati"),
    KOREA_DEMOCRATIC_PEOPLES_REPUBLIC_OF("KP", "PRK", "Korea, Democratic People's Republic of"),
    KOREA_REPUBLIC_OF("KR", "KOR", "Korea, Republic of"),
    KUWAIT("KW", "KWT", "Kuwait"),
    KYRGYZSTAN("KG", "KGZ", "Kyrgyzstan"),
    LAO_PEOPLES_DEMOCRATIC_REPUBLIC("LA", "LAO", "Lao People's Democratic Republic"),
    LATVIA("LV", "LVA", "Latvia"),
    LEBANON("LB", "LBN", "Lebanon"),
    LESOTHO("LS", "LSO", "Lesotho"),
    LIBERIA("LR", "LBR", "Liberia"),
    LIBYA("LY", "LBY", "Libya"),
    LIECHTENSTEIN("LI", "LIE", "Liechtenstein"),
    LITHUANIA("LT", "LTU", "Lithuania"),
    LUXEMBOURG("LU", "LUX", "Luxembourg"),
    MACAO("MO", "MAC", "Macao"),
    MADAGASCAR("MG", "MDG", "Madagascar"),
    MALAWI("MW", "MWI", "Malawi"),
    MALAYSIA("MY", "MYS", "Malaysia"),
    MALDIVES("MV", "MDV", "Maldives"),
    MALI("ML", "MLI", "Mali"),
    MALTA("MT", "MLT", "Malta"),
    MARSHALL_ISLANDS("MH", "MHL", "Marshall Islands"),
    MARTINIQUE("MQ", "MTQ", "Martinique"),
    MAURITANIA("MR", "MRT", "Mauritania"),
    MAURITIUS("MU", "MUS", "Mauritius"),
    MAYOTTE("YT", "MYT", "Mayotte"),
    MEXICO("MX", "MEX", "Mexico"),
    MICRONESIA_FEDERATED_STATES_OF("FM", "FSM", "Micronesia, Federated States of"),
    MOLDOVA_REPUBLIC_OF("MD", "MDA", "Moldova, Republic of"),
    MONACO("MC", "MCO", "Monaco"),
    MONGOLIA("MN", "MNG", "Mongolia"),
    MONTENEGRO("ME", "MNE", "Montenegro"),
    MONTSERRAT("MS", "MSR", "Montserrat"),
    MOROCCO("MA", "MAR", "Morocco"),
    MOZAMBIQUE("MZ", "MOZ", "Mozambique"),
    MYANMAR("MM", "MMR", "Myanmar"),
    NAMIBIA("NA", "NAM", "Namibia"),
    NAURU("NR", "NRU", "Nauru"),
    NEPAL("NP", "NPL", "Nepal"),
    NETHERLANDS_KINGDOM_OF_THE("NL", "NLD", "Netherlands, Kingdom of the"),
    NEW_CALEDONIA("NC", "NCL", "New Caledonia"),
    NEW_ZEALAND("NZ", "NZL", "New Zealand"),
    NICARAGUA("NI", "NIC", "Nicaragua"),
    NIGER("NE", "NER", "Niger"),
    NIGERIA("NG", "NGA", "Nigeria"),
    NIUE("NU", "NIU", "Niue"),
    NORFOLK_ISLAND("NF", "NFK", "Norfolk Island"),
    NORTH_MACEDONIA("MK", "MKD", "North Macedonia"),
    NORTHERN_MARIANA_ISLANDS("MP", "MNP", "Northern Mariana Islands"),
    NORWAY("NO", "NOR", "Norway"),
    OMAN("OM", "OMN", "Oman"),
    PAKISTAN("PK", "PAK", "Pakistan"),
    PALAU("PW", "PLW", "Palau"),
    PALESTINE_STATE_OF("PS", "PSE", "Palestine, State of"),
    PANAMA("PA", "PAN", "Panama"),
    PAPUA_NEW_GUINEA("PG", "PNG", "Papua New Guinea"),
    PARAGUAY("PY", "PRY", "Paraguay"),
    PERU("PE", "PER", "Peru"),
    PHILIPPINES("PH", "PHL", "Philippines"),
    PITCAIRN("PN", "PCN", "Pitcairn"),
    POLAND("PL", "POL", "Poland"),
    PORTUGAL("PT", "PRT", "Portugal"),
    PUERTO_RICO("PR", "PRI", "Puerto Rico"),
    QATAR("QA", "QAT", "Qatar"),
    REUNION("RE", "REU", "Réunion"),
    ROMANIA("RO", "ROU", "Romania"),
    RUSSIAN_FEDERATION("RU", "RUS", "Russian Federation"),
    RWANDA("RW", "RWA", "Rwanda"),
    SAINT_BARTHELEMY("BL", "BLM", "Saint Barthélemy"),
    SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA("SH", "SHN", "Saint Helena, Ascension and Tristan da Cunha"),
    SAINT_KITTS_AND_NEVIS("KN", "KNA", "Saint Kitts and Nevis"),
    SAINT_LUCIA("LC", "LCA", "Saint Lucia"),
    SAINT_MARTIN_FRENCH_PART("MF", "MAF", "Saint Martin (French part)"),
    SAINT_PIERRE_AND_MIQUELON("PM", "SPM", "Saint Pierre and Miquelon"),
    SAINT_VINCENT_AND_THE_GRENADINES("VC", "VCT", "Saint Vincent and the Grenadines"),
    SAMOA("WS", "WSM", "Samoa"),
    SAN_MARINO("SM", "SMR", "San Marino"),
    SAO_TOME_AND_PRINCIPE("ST", "STP", "Sao Tome and Principe"),
    SAUDI_ARABIA("SA", "SAU", "Saudi Arabia"),
    SENEGAL("SN", "SEN", "Senegal"),
    SERBIA("RS", "SRB", "Serbia"),
    SEYCHELLES("SC", "SYC", "Seychelles"),
    SIERRA_LEONE("SL", "SLE", "Sierra Leone"),
    SINGAPORE("SG", "SGP", "Singapore"),
    SINT_MAARTEN_DUTCH_PART("SX", "SXM", "Sint Maarten (Dutch part)"),
    SLOVAKIA("SK", "SVK", "Slovakia"),
    SLOVENIA("SI", "SVN", "Slovenia"),
    SOLOMON_ISLANDS("SB", "SLB", "Solomon Islands"),
    SOMALIA("SO", "SOM", "Somalia"),
    SOUTH_AFRICA("ZA", "ZAF", "South Africa"),
    SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS("GS", "SGS", "South Georgia and the South Sandwich Islands"),
    SOUTH_SUDAN("SS", "SSD", "South Sudan"),
    SPAIN("ES", "ESP", "Spain"),
    SRI_LANKA("LK", "LKA", "Sri Lanka"),
    SUDAN("SD", "SDN", "Sudan"),
    SURINAME("SR", "SUR", "Suriname"),
    SVALBARD_AND_JAN_MAYEN("SJ", "SJM", "Svalbard and Jan Mayen"),
    SWEDEN("SE", "SWE", "Sweden"),
    SWITZERLAND("CH", "CHE", "Switzerland"),
    SYRIAN_ARAB_REPUBLIC("SY", "SYR", "Syrian Arab Republic"),
    TAIWAN_PROVINCE_OF_CHINA("TW", "TWN", "Taiwan, Province of China"),
    TAJIKISTAN("TJ", "TJK", "Tajikistan"),
    TANZANIA_UNITED_REPUBLIC_OF("TZ", "TZA", "Tanzania, United Republic of"),
    THAILAND("TH", "THA", "Thailand"),
    TIMOR_LESTE("TL", "TLS", "Timor-Leste"),
    TOGO("TG", "TGO", "Togo"),
    TOKELAU("TK", "TKL", "Tokelau"),
    TONGA("TO", "TON", "Tonga"),
    TRINIDAD_AND_TOBAGO("TT", "TTO", "Trinidad and Tobago"),
    TUNISIA("TN", "TUN", "Tunisia"),
    TURKIYE("TR", "TUR", "Türkiye"),
    TURKMENISTAN("TM", "TKM", "Turkmenistan"),
    TURKS_AND_CAICOS_ISLANDS("TC", "TCA", "Turks and Caicos Islands"),
    TUVALU("TV", "TUV", "Tuvalu"),
    UGANDA("UG", "UGA", "Uganda"),
    UKRAINE("UA", "UKR", "Ukraine"),
    UNITED_ARAB_EMIRATES("AE", "ARE", "United Arab Emirates"),
    UNITED_KINGDOM_OF_GREAT_BRITAIN_AND_NORTHERN_IRELAND("GB", "GBR", "United Kingdom of Great Britain and Northern Ireland"),
    UNITED_STATES_OF_AMERICA("US", "USA", "United States of America"),
    UNITED_STATES_MINOR_OUTLYING_ISLANDS("UM", "UMI", "United States Minor Outlying Islands"),
    URUGUAY("UY", "URY", "Uruguay"),
    UZBEKISTAN("UZ", "UZB", "Uzbekistan"),
    VANUATU("VU", "VUT", "Vanuatu"),
    VENEZUELA_BOLIVARIAN_REPUBLIC_OF("VE", "VEN", "Venezuela, Bolivarian Republic of"),
    VIET_NAM("VN", "VNM", "Viet Nam"),
    VIRGIN_ISLANDS_BRITISH("VG", "VGB", "Virgin Islands (British)"),
    VIRGIN_ISLANDS_US("VI", "VIR", "Virgin Islands (U.S.)"),
    WALLIS_AND_FUTUNA("WF", "WLF", "Wallis and Futuna"),
    WESTERN_SAHARA("EH", "ESH", "Western Sahara"),
    YEMEN("YE", "YEM", "Yemen"),
    ZAMBIA("ZM", "ZMB", "Zambia"),
    ZIMBABWE("ZW", "ZWE", "Zimbabwe")

}
